### ISSUE TITLE
how to use https address

### ISSUE THREAD

**Issue by trdem** [yyyyu/react-native-geetest-sensebot#1]
hello yyyyu,
  recently , i use your react-native-geetest-sensebot ,but i found o problem, when i use  https address for 'GeetestSensebot.configApi', i got a warining which told me i can not use https address , i tried to find how to add https address , but i failed , can you tell  me , what shoud i do  to  fix this problem?
 thank you very much

**Comment by yyyyu** [comment]
configApi 需要同时传入 api1 api2 [两个地址](https://github.com/yyyyu/react-native-geetest-sensebot#js-api)，如果不是这个原因，请提供一下截图及rn版本帮助我判断问题

https://github.com/yyyyu/RNModuleTest/tree/react-native-geetest-sensebot 这个是我测试用的项目，希望对你有帮助

**Comment by trdem** [comment]
![image](https://user-images.githubusercontent.com/27819098/46209068-47e06d80-c35f-11e8-9c3d-d76e42f0de7e.png)我用的是这个
    // 初始化极验api
    const api1 = 'https://cn.bitforex.com/server/user_account.act?cmd=requestCheckCode&type=login'
    const api2 = 'https://cn.bitforex.com/server/user_account.act?cmd=requestCheckCode&type=login'
    GeetestSensebot.configApi(api1, api2)
然后在这里
![image](https://user-images.githubusercontent.com/27819098/46209342-32b80e80-c360-11e8-94b4-7f8298fecd0b.png)
校验api地址的时候
export const configApi = (api1, api2) => {
  validUrl(api1)
  GSConfig.api1 = api1
  validUrl(api2)
  GSConfig.api2 = api2
}
方法validUrl会报错
![image](https://user-images.githubusercontent.com/27819098/46209392-55e2be00-c360-11e8-8ae4-713ec0721250.png)
import invariant from 'invariant'

export default arg => {
  invariant(
    typeof arg === 'string',
    'expect url is string type, but get %s', typeof arg
  )
  invariant(
    /^https?:\/\//.test(arg),
    'expect url is valid http address, but get %s', arg
  )
}
不支持https，看了后续的没找到配置的地方  请教下这个问题如何解决 万分感谢

**Comment by yyyyu** [comment]
并非是url校验不通过，而是因为你提供的api返回数据结构和极验提供的结构不一致，需要自行修改传入极验SDK中的参数才能正确启动，[替换方式这里](https://github.com/yyyyu/react-native-geetest-sensebot#captcha-%E8%BF%9B%E8%A1%8C%E8%A1%8C%E4%B8%BA%E8%AE%A4%E8%AF%81)

**极验验证流程:** 调用api1 -> ***得到 { success, gt, challenge }(这步出了问题)*** -> 传入客户端SDK -> SDK内部和极验服务器进行行为认证 -> 返回 { geetest_challenge, geetest_seccode, geetest_validate } -> 利用客户端SDK返回的数据调用api2 -> 服务端收到api2请求参数后与极验服务器进行认证 -> 将验证结果返回给你

示例代码
```javascript 
import { AppRegistry } from 'react-native'
import GeetestSensebot, { GSError, ERROR_TYPE } from '@yyyyu/react-native-geetest-sensebot'

const main = async () => {
  const api1 = 'api1 address'
  const api2 = 'api2 address'
  GeetestSensebot.configApi(api1, api2)
  GeetestSensebot.setMaskColor('#0004')

  try {
    const result = await GeetestSensebot.captcha({
      // 针对你提api特定response处理
      api1RespHandler: async api1Resq => {
        const { data } = await api1Resq.json()
        return data
      }
    })
    console.log(result)
  } catch (e) {
    if (e instanceof GSError) {
      const { errCode, errMsg } = e
      switch (errCode) {
        case ERROR_TYPE.API1:
          console.error('api1 error %s', errMsg)
          break
        case ERROR_TYPE.CAPTCHA:
          console.error('captcha error %s', errMsg)
          break
        case ERROR_TYPE.API2:
          console.error('api2 error %s', errMsg)
          break
      }
    } else {
      console.error(e.message)
    }
  }
}

const App = () => {
  main()
  return null
}

AppRegistry.registerComponent('RNModuleTest', () => App)
```

<img src="https://user-images.githubusercontent.com/15168529/46212871-a7dc1180-c369-11e8-8917-8fd94aa69bfa.png" alt="example" width="300" />

**Comment by yyyyu** [comment]
注意隐藏 api 信息

**Comment by trdem** [comment]
感谢您的回复！
昨天比较匆忙，问题没有详细描述清楚，下面是我遇到问题的流程：
![image](https://user-images.githubusercontent.com/27819098/46239048-96285780-c3c5-11e8-9bef-1ac123eaca48.png)
这个是在进需要校验的页面初始化的时候 ，就会报这个错误，例如我在登录页面使用http没有问题的，但是使用了https就会报这个问题，当我尝试注释掉validUrl里面的检查后 不会报这个错误，然后发起请求的话就会有如下的问题出现
![image](https://user-images.githubusercontent.com/27819098/46239083-2c5c7d80-c3c6-11e8-8c79-8ecafacb062a.png)
下面是对api的返回值做的处理
![image](https://user-images.githubusercontent.com/27819098/46239108-6c236500-c3c6-11e8-8454-11f68d63e681.png)
http下得到的是{ success, gt, challenge }这种形式，  但是我这里在https下请求失败 没有获取到需要的值
3q

**Comment by yyyyu** [comment]
原来是这样，我看到你使用的是windows操作系统，很可能是正则写法不同，可以帮我在你的环境中测试一下下面两种写法校验结果吗，这有助于我完善这个项目

```javascript
/^https?:\/\//.test('https://www.example.com')
RegExp('^https?://').test('https://www.example.com')
```

下面警告信息并非是报错，而是js语法问题
![image](https://user-images.githubusercontent.com/15168529/46239816-b27dc180-c3d0-11e8-89a6-35947ae949c6.png)

response.json() 返回 promise, 你可以用 await response.json() 直接拿到结果，并将此行代码放在 try {} catch(e) {} 中，或者加 .catch() 捕获可能会产生的错误

**Comment by trdem** [comment]
刚刚经过测试，使用了大佬的方法
![image](https://user-images.githubusercontent.com/27819098/46240102-1609ee00-c3d5-11e8-98a6-d178ed43b5ab.png)
可以正常使用https的请求了
同时检测了两种正则的校验结果 返回的都是 true
![image](https://user-images.githubusercontent.com/27819098/46240115-58cbc600-c3d5-11e8-80c3-4c53b76f9acf.png)

![image](https://user-images.githubusercontent.com/27819098/46240113-4ce00400-c3d5-11e8-9c3b-57d25449ecdd.png)
再次感谢您的回复和指导

**Comment by yyyyu** [comment]
那我先关闭这个issue了，如果有疑问可以随时打开

**Comment by trdem** [comment]
谢谢！！！
