### ISSUE TITLE
README不完善

### ISSUE THREAD

**Issue by playscforever** [yyyyu/react-native-geetest-sensebot#4]
http://npm.taobao.org/package/@yyyyu/react-native-geetest-sensebot
目前github上的README还没有上面这个详细，照着github上的来Android和iOS都无法正确运行，反倒看了下上面的和别人fork的项目才跑起来。

**Comment by yyyyu** [comment]
抱歉，文档是对的， [npm](https://www.npmjs.com/package/@yyyyu/react-native-geetest-sensebot) 上忘记发布新版本，结果用旧的代码新的文档导致运行失败

**Comment by playscforever** [comment]
已经按照旧的文档接入了，升级之后会有影响吗？

**Comment by yyyyu** [comment]
功能上没有影响, 如果没发布建议更新一下

**Comment by yyyyu** [comment]
先把这个 issue 关掉了，有其它问题可以随时打开
