### ISSUE TITLE
偶尔会调不起来滑块页面，直接就拿到错误的geetest_challenge

### ISSUE THREAD

**Issue by playscforever** [yyyyu/react-native-geetest-sensebot#5]

**Comment by yyyyu** [comment]
注意catch报错，默认快速连续点击，后续都会报错 Errors.DUPLICATE_START，也有可能是第一步服务器与极验通信返回参数包含错误状态的 challenge 等信息，如果不是这些问题，需要提供更详细的调用参数才能找到问题

**Comment by playscforever** [comment]
@yyyyu 嗯，看了下应该是连续点击的问题，另外我试了下语言设置为英语的时候，文字都变成英语了，可是图片还是中文的（”拖动下方滑块“） 这是sdk自己的问题吗？

**Comment by yyyyu** [comment]
SDK的问题
