### ISSUE TITLE
framework not found GT3Captcha

### ISSUE THREAD

**Issue by jamestechvus** [yyyyu/react-native-geetest-sensebot#6]
ld: framework not found GT3Captcha
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![Screenshot 2019-07-08 at 5 44 26 PM](https://user-images.githubusercontent.com/50881040/60800626-1c20cc80-a1a8-11e9-96af-0d44d32abd9a.png)

**Comment by yyyyu** [comment]
add `$(PROJECT_DIR)/../node_modules/@yyyyu/react-native-geetest-sensebot/ios/SDK` to **Framework Search Paths** in **Build Settings** tab, just like [this](https://stackoverflow.com/questions/31896667/how-to-add-the-parent-path-to-realmswift-framework-in-the-framework-search-path)

**Comment by jamestechvus** [comment]
I abble to build my project now. But when i insert this line
`import * as RNGeetestSensebot from '@yyyyu/react-native-geetest-sensebot'`

Native module cannot be null. Error occured

**Error page from my device**
![IMG_7C98EB0E793B-1](https://user-images.githubusercontent.com/50881040/60940354-ce25d900-a30d-11e9-886a-939b3126df38.jpeg)

**Console error message**
![Screenshot 2019-07-10 at 12 26 25 PM](https://user-images.githubusercontent.com/50881040/60940458-22c95400-a30e-11e9-8f91-5fe33952203f.png)

**Comment by yyyyu** [comment]
it looks like link failed.
have you ever been run `react-native link @yyyyu/react-native-geetest-sensebot` to link library?

you can unlink firstly `react-native unlink @yyyyu/react-native-geetest-sensebot`, then relink by run  `react-native link @yyyyu/react-native-geetest-sensebot` or [manual link](https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking)

**Comment by jamestechvus** [comment]
I done the manual link by adding libRCTGeeTestSensebot.a into **Link Binary With Libraries** section.
But everytime i run/build the project, it's failed without any error.

<img width="423" alt="Screenshot 2019-07-10 at 10 09 12 PM" src="https://user-images.githubusercontent.com/50881040/60975977-6d26f100-a35f-11e9-8517-72c0c1476217.png">

<img width="600" alt="Screenshot 2019-07-10 at 10 06 53 PM" src="https://user-images.githubusercontent.com/50881040/60975822-26d19200-a35f-11e9-9efc-f67a387fad9a.png">

**Comment by yyyyu** [comment]
try add it to **Linked Frameworks and Libraries** section in General tab, like this
![image](https://user-images.githubusercontent.com/15168529/60979379-3227bc00-a365-11e9-82af-7945b499e0f6.png)

**Comment by jamestechvus** [comment]
My project is using RN v0.57.1. I tried fresh install again but it still showing me same error as below image.

<img width="275" alt="Screenshot 2019-07-11 at 2 01 49 AM" src="https://user-images.githubusercontent.com/50881040/60993537-3a8df000-a381-11e9-9980-1b6cfda0b2e7.png">

**Comment by yyyyu** [comment]
the reason for this problem is this library depend on react-native library, if you set up project by `react-native init XXX`, React and other relative libraries were added to your project. when project compile, React will copy its header files(just like declaration file in typescript) to your [project include directory](https://mmquant.net/working-directories-and-build-locations-with-xcode9-and-cpp/), so the library can be compiled right. i don't know why you project didn't do this, sry i have no macbook currently. you can check project include directory if react directory in it, btw, `<React/RCTConvert.h>` correspond to `XXX/include/React/RCTConvert.h` file

**Comment by jamestechvus** [comment]
I managed to show the Geetest modal but it always auto close after **Analysing...**. I followed exactly the code from your tutorial.

Following is the message i get from console (onEvent) :-

`Validate failed, reason: _21, {
    NSErrorFailingURLStringKey = "https://18.136.114.111/get.php?gt=4faf9dd37eb683586977947ce87a866a&challenge=db6591069310c69cf5727ccc06849892&lang=en-ph&client_type=ios&w=z33h(orseIRe5Vw7053BwIUot3Tpm4XD7HQT(6hPQPA.c126d5bdccd783820910cb219a990fadadff3e2b823d5c07e5744883d1b39f4e7bd41744a17f6a7ac957be96a5e6c0b19b6fa3366d7d6ceeea6baf791d6982c661489718dd87846c1c4b2ab19be65c048aa5ad1ef7f4a179b9edad44754cc8a719b27e6df83e71ddeae20790cc02b2786d57f5eba176f8bd1717dbd7f07f90ec";
    NSLocalizedDescription = "not proof";
    "error_code" = "error_21";
    geetest = "apiService:didFailWithError:";
    metadata = "{\"user_error\": \"Error\", \"status\": \"error\", \"error\": \"not proof\", \"error_code\": \"error_21\"}";
    "user_error" = Error;
}`

**Comment by yyyyu** [comment]
you have to keep api1 response struct like this
```javascript
// https://www.geetest.com/demo/gt/register-test
let api1Result = {
  "success": 1,
  "challenge": "f53e91f1df8b5bcab012caea32b1d3de",
  "gt": "4faf9dd37eb683586977947ce87a866a",
  "new_captcha": true
}
```
from your log, it seems like some error on your server
